import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';

import { ColorSchemeScript, MantineProvider , createTheme } from '@mantine/core';
import { ClerkProvider } from '@clerk/nextjs'
import NavBarComponent from "@/components/navBarComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: 'Open Sans, sans-serif',
  primaryColor: 'blue',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className=" ">
       <MantineProvider 
        theme={theme}
        defaultColorScheme="light"
        >
    
      
       <NavBarComponent/>
          {children}
       
     
      </MantineProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
